### PR TITLE
Problem: method eth_chainId crashed occasionally

### LINKED ISSUE #515: Problem: method eth_chainId crashed occasionally
params could be nil when failed to load state since CatchupWAL target in the [future](https://github.com/crypto-org-chain/cronos/blob/737bd9e4f197357e9170d7c554ef10038985280f/memiavl/multitree.go#L336), crash on runtime error occurs: invalid memory address or nil pointer dereference

<Details>
goroutine 3345 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
	github.com/ethereum/go-ethereum/rpc/service.go:199 +0x74
panic({0x4d960c0?, 0x95b3990?})
	runtime/panic.go:770 +0x124
github.com/ethereum/go-ethereum/params.(*ChainConfig).IsEIP155(...)
	github.com/ethereum/go-ethereum/params/config.go:572
github.com/evmos/ethermint/rpc/backend.(*Backend).ChainID(0x400186c588)
	github.com/evmos/ethermint/rpc/backend/chain_info.go:55 +0x140
github.com/evmos/ethermint/rpc/namespaces/ethereum/eth.(*PublicAPI).ChainId(0x40017a9440)
	github.com/evmos/ethermint/rpc/namespaces/ethereum/eth/api.go:353 +0x5c
reflect.Value.call({0x4002710690?, 0x40024dc6b0?, 0x30?}, {0x537ad14, 0x4}, {0x400333e360, 0x1, 0x434e754?})
	reflect/value.go:596 +0x970
reflect.Value.Call({0x4002710690?, 0x40024dc6b0?, 0x0?}, {0x400333e360?, 0x140?, 0x4002480008?})
	reflect/value.go:380 +0x94
github.com/ethereum/go-ethereum/rpc.(*callback).call(0x40012ea480, {0x7413b68, 0x4001c78a00}, {0x40008881b0, 0xb}, {0x98f71e0, 0x0, 0x43471cc?})
	github.com/ethereum/go-ethereum/rpc/service.go:205 +0x2d0
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0x40008881c0?, {0x7413b68?, 0x4001c78a00?}, 0x4002221730, 0x0?, {0x98f71e0?, 0x0?, 0x0?})
	github.com/ethereum/go-ethereum/rpc/handler.go:513 +0x40
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0x400195f050, 0x400333e2a0, 0x4002221730)
	github.com/ethereum/go-ethereum/rpc/handler.go:459 +0x1d8
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0x400195f050, 0x400333e2a0, 0x4002221730)
	github.com/ethereum/go-ethereum/rpc/handler.go:420 +0x1d0
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0x400333e2a0)
	github.com/ethereum/go-ethereum/rpc/handler.go:256 +0x150
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
	github.com/ethereum/go-ethereum/rpc/handler.go:348 +0xbc
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc in goroutine 255
	github.com/ethereum/go-ethereum/rpc/handler.go:344 +0x84
</Details>

### PR DESCRIPTION
**Pull request by mmsqe**
add fallback default config to ensure no panic in IsEIP155 check

Closes: https://github.com/crypto-org-chain/ethermint/issues/515

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: rpc/backend/chain_info.go [hunk 1]
```diff
@@ -52,7 +52,11 @@ func (b *Backend) ChainID() (*hexutil.Big, error) {
 		return (*hexutil.Big)(eip155ChainID), nil
 	}
 
-	if config := b.ChainConfig(); config.IsEIP155(new(big.Int).SetUint64(uint64(bn))) {
+	config := b.ChainConfig()
+	if config == nil {
+		config = evmtypes.DefaultChainConfig().EthereumConfig(eip155ChainID)
```
Comment (yihuang) [inline rpc/backend/chain_info.go:57]:
```suggestion
		return (*hexutil.Big)(config.ChainID), nil
```

**Review by yihuang — APPROVED** [review]
